apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: onaxi9z2s-dotnet-basic
  janus-idp.io/tekton: onaxi9z2s-dotnet-basic
  backstage.io/kubernetes-id: onaxi9z2s-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: onaxi9z2s-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
